#Project Euler 2
#19/08/13

# "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."


fib=[1, 2]
fib2=[]
counter=0
while fib[-1]<4000000:
	counter+=1
	l=len(fib)
	n=fib[l-2]+fib[l-1]
	fib.append(n)
	if counter==3 and n<4000000:
		fib2.append(n)
		counter=0
print(sum(fib2)+2)

